#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

echo 'Running pre-commit tasks...'
echo '-----------------------------'
echo '1. Running code formatter...'
dotnet format --verify-no-changes >> /dev/null
echo '2. Building solution...'
dotnet build >> /dev/null
echo '3. Running unit tests...'
dotnet test --no-build --verbosity normal
echo 'Pre-commit tasks completed successfully!'
